universe = parallel

executable = openmpiscript.sh

arguments = bin/KMEANS_mpi+omp "./test_files/input100D2.inp" 100 150 0.01 0.01 "./bin/out/KMEANS_mpi+omp_5"

should_transfer_files = YES

transfer_input_files = bin/KMEANS_mpi+omp

when_to_transfer_output = on_exit_or_evict

output = logs/multiple_lib_out.$(NODE)
error = logs/multiple_lib_err.$(NODE)
log = logs/multiple_lib_log

machine_count = 8
request_cpus = 32

getenv = True

queue